name: UPSERT workflow
on:
  push:
    branches:
     - main
jobs:
    create-entity-in-port-and-update-run:
        runs-on: ubuntu-latest

        steps:
            - name: Set up jq
              run: |
                sudo apt-get update
                sudo apt-get install jq -y

            - name: Print Payload Properties
              run: |
                echo "Payload properties and values:"
                echo "${{ inputs.port_payload }}" | jq
