name: Argocd Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ArgoCD CLI
        run: |
          curl -LO https://github.com/argoproj/argo-cd/releases/download/v2.1.5/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Login to ArgoCD
        run: argocd login --username "admin" --password "3n9rn8SHGS3csUXt" --server http://a643e055e05314dfa8ab628ed545b9f7-783703239.us-east-1.elb.amazonaws.com

     
